global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'k-webserver'
    static_configs:
      - targets: ['localhost:3000']  # Will use WEBSERVER_PORT from .env
    metrics_path: '/metrics'
    scrape_interval: 15s
